# Generated by Django 4.0.3 on 2022-04-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reviewed',
            field=models.CharField(choices=[('N', 'No'), ('Y', 'Yes')], max_length=10),
        ),
    ]
