# Generated by Django 4.0.3 on 2022-04-12 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_report_reviewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='reports',
            field=models.ManyToManyField(blank=True, to='main_app.report'),
        ),
        migrations.AlterField(
            model_name='report',
            name='cadence',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Bi-Weekly', 'Bi-Weekly'), ('Daily', 'Daily'), ('Weekly', 'Weekly')], max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='reviewed',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=10),
        ),
    ]
