# Generated by Django 4.0.3 on 2022-04-12 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_location_reports_alter_report_cadence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='cadence',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Bi-Weekly', 'Bi-Weekly'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='notes',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='report',
            name='reviewed',
            field=models.CharField(choices=[('N', 'No'), ('Y', 'Yes')], max_length=10),
        ),
    ]
